export const ROUTES = {
    HOME: "/",
    REVEAL_IMAGES: "/reveal-images",
    SPLIT_VIGLETTA: "/split-vigletta",
    MASK_CURSOR: "/mask-cursor",
    FRAMER_MODAL: "/framer-modal",
    SCROLL_PROGRESS: "/scroll-progress",
    MAKE_PROGRESS_WHEN_IN_VIEW: "/make-progress-when-in-view",
    SCROLL_TEXT_WITH_SCROLLING: "/scroll-text-with-scrolling",
    REVEAL_TEXT_ON_VIEW: "/reveal-text-on-view",
    WELCOME_PAGE: "/welcome-here",
    ONSCROLL_ZOOM: "/on-scroll-zoom",
    ANIMATED_BUTTONS: "/animated-buttons",
    OPEN_LIST_ANIMATION: "/open-list-animation",
    FRAMER_MOTION: "/framer-motion",
    ADD_REMOVE_ELEMENT: "/add-remove-element",
}